name: nextjs

description: |
  Example component that includes a React frontend

homepage: https://github.com/architect-templates/nextjs

keywords:
  - nextjs
  - react

# Add secrets to be used by different services. For more information:
# https://docs.architect.io/deployments/secrets/
secrets: # TODO: remove?
  service_api_port:
    description: Port for Lightweight-api service
    default: 3000

## Want to learn about dependencies? Follow along with "Adding a Dependency" in the README
##   then uncomment the two lines below and uncomment line 41 (REACT_APP_API_ADDR)
# dependencies:
#   node-rest-api: latest # TODO

# Below are the configured services for the React component. Note that the actual
# react application we're working on is defined as a service on line 22
# For more info - https://docs.architect.io/components/services/
services:
  ### This service is the actual React component ###
  app:
    # Build context is the location of your application relative to the architect.yml file
    build:
      context: ./
      args:
        NODE_ENV: production # TODO: does next want one or the other?
    # Main interface port used to help define the url in the `interfaces` block on line 53
    interfaces:
      main: 3000
    # Set environment variables for your application here
    environment:
      API_ADDR: ${{ services.lightweight-api.interfaces.http.url }}
      NODE_ENV: production
    # The liveness_probe makes sure the application is healthy - if not, it will re-start the application
    liveness_probe:
      command: curl --fail localhost:3000/
      initial_delay: 30s
      interval: 30s
      failure_threshold: 3
    # We want our app to start up after the db is running so that we can connect to it on startup!
    # This block contains a list of services we need to start before 'app' starts.
    depends_on:
      - lightweight-api
    # Debug block is used to enable hot-reloading to make real-time changes to an
    #   application while running `architect dev`. For more info, see -
    #   https://docs.architect.io/components/local-configuration/#hot-reloading
    debug:
      # command: npm run dev # TODO: remove?
      build:
        # Use a different Dockerfile for local development that supports hot reloading
        dockerfile: Dockerfile.dev
        args:
          NODE_ENV: development # TODO: does next want one or the other?
      environment:
        NODE_ENV: development
      volumes:
        pages:
          # The `WORKDIR` defined in the Dockerfile (/app) + name of source code directory (/pages)
          mount_path: /app/pages
          # Path to source code relative to the architect.yml file (/src)
          host_path: ./pages
        lib:
          mount_path: /app/lib
          host_path: ./lib
        styles:
          mount_path: /app/styles
          host_path: ./styles

  #  This is an additional service that adds a lightweight API to the
  #   application to show off Architect's support for microservice architecture
  #   through service discovery. For more info, check out:
  #   https://docs.architect.io/components/service-discovery/
  lightweight-api:
    image: registry.gitlab.com/architect-io/artifacts/nodejs-hello-world:latest # TODO: ask about hosting this under architect account on gitlab?
    interfaces:
      http: ${{ secrets.service_api_port }}

# interfaces are used to expose our application to the gateway, allowing
#   other services and dependencies to connect to one another.
#   For more info - https://docs.architect.io/components/interfaces/
interfaces:
  # Interface for our main NextJS Application
  app:
    url: ${{ services.app.interfaces.main.url }}
    ingress:
      subdomain: app
  # # Interface for our API layer
  # lightweight-api:
  #   url: ${{ services.lightweight-api.interfaces.http.url }}
  #   ingress:
  #     subdomain: service-api
